/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppPlaylistsIndexRouteImport } from './routes/_app.playlists.index'
import { Route as AppPlaylistsIdRouteImport } from './routes/_app.playlists.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsIndexRoute = AppPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistsIdRoute = AppPlaylistsIdRouteImport.update({
  id: '/playlists/$id',
  path: '/playlists/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/favorites': typeof AppFavoritesRoute
  '/library': typeof AppLibraryRoute
  '/search': typeof AppSearchRoute
  '/playlists/$id': typeof AppPlaylistsIdRoute
  '/playlists/': typeof AppPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof AppFavoritesRoute
  '/library': typeof AppLibraryRoute
  '/search': typeof AppSearchRoute
  '/': typeof AppIndexRoute
  '/playlists/$id': typeof AppPlaylistsIdRoute
  '/playlists': typeof AppPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/playlists/$id': typeof AppPlaylistsIdRoute
  '/_app/playlists/': typeof AppPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/library'
    | '/search'
    | '/playlists/$id'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/library'
    | '/search'
    | '/'
    | '/playlists/$id'
    | '/playlists'
  id:
    | '__root__'
    | '/_app'
    | '/_app/favorites'
    | '/_app/library'
    | '/_app/search'
    | '/_app/'
    | '/_app/playlists/$id'
    | '/_app/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/': {
      id: '/_app/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof AppPlaylistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlists/$id': {
      id: '/_app/playlists/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof AppPlaylistsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlaylistsIdRoute: typeof AppPlaylistsIdRoute
  AppPlaylistsIndexRoute: typeof AppPlaylistsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlaylistsIdRoute: AppPlaylistsIdRoute,
  AppPlaylistsIndexRoute: AppPlaylistsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
